PUT http://localhost:8080/api/products/1 HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJuYW1lIjoiQWRtaW4gVXNlciIsImVtYWlsIjoiYWRtaW5AbWFpbC5ydSIsInN0YXR1cyI6ImFkbWluIiwiZXhwIjoxNzYxNzIzNTYyfQ.nFcc91wyykCeSer1lnF4UskZ7zwLcCON4xDC9AhM3hg

{
    "name": "Яблоки Голден",
    "category": "Яблоки",
    "price": 99.99,
    "quantity": 80
}